controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_product:
        path: /produits/{query}
        controller: App\Controller\ProduitsController::search

