# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_product:
        path: /produits/{query}
        controller: App\Controller\ProduitsController::search

panier:
    path: /panier
    controller: App\Controller\PanierController::index

panier_ajouter:
    path: '/panier/ajouter/{id}'
    controller: 'App\Controller\PanierController::ajouterProduit'
